[azure_cv]
api_key = "YOUR_AZURE_CV_KEY"
endpoint = "YOUR_AZURE_CV_ENDPOINT"

[azure_openai]
api_version = "2024-02-15-preview"
endpoint = "YOUR_AZURE_OPENAI_ENDPOINT"
api_key = "YOUR_AZURE_OPENAI_KEY"
deployment_name = "YOUR_DEPLOYMENT_NAME"

[spotify]
client_id = "YOUR_SPOTIFY_CLIENT_ID"
client_secret = "YOUR_SPOTIFY_CLIENT_SECRET"

