[azure_cv]
api_key = "4tyRISjNJEqLwFg4V3WEWZDLo2ysbznw1DabNKh1sB6XdbJTwW79JQQJ99BEACYeBjFXJ3w3AAAFACOGJfjq"
endpoint = "https://techinno.cognitiveservices.azure.com/"

[azure_openai]
api_key = "EsXkEhXWDTUyNV7MJD7V67z6AJYcPIQd8ysyTeBQd2fQcx18eELhJQQJ99BEACYeBjFXJ3w3AAABACOGeK6j"
endpoint = "https://techinno2.openai.azure.com/"
deployment_name = "Microsoft.CognitiveServicesOpenAI-20250516145908"
model = "gpt-4"
api_version = "2024-02-15-preview"

[spotify]
client_id = "a3b3f365b7b74bc6a3a6f27e296732d4"
client_secret = "f4b4a9850fc24184957cc03e81955bcf"

